### ISSUE TITLE
Update to scala 2.12

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/Scalatex#38]
Would it be possible to publish scalatex against scala 2.12?

Cheers,
Romin

**Comment by romainreuillon** [comment]
Only the only thing missing is a stable release for amonite and I think scalatex could support scala 2.12:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lihaoyi#ammonite-ops_2.12;0.8.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lihaoyi:ammonite-ops_2.12:0.8.0 (/home/reuillon/Documents/Recherche/Projects/Scalatex/build.sbt#L70)
[warn] 		  +- com.lihaoyi:scalatex-site_2.12:0.3.7-SNAPSHOT
```

**Comment by lihaoyi** [comment]
the latest unstable release of Ammonite supports 2.12; i'll let it bake for a week or two and if there aren't any issues, i'll give it a number and then release scalatex depending on it

**Comment by romainreuillon** [comment]
Sounds great!

**Comment by xeno-by** [comment]
+1

**Comment by romainreuillon** [comment]
Any news of the release?

**Comment by lihaoyi** [comment]
Currently it's blocked on https://github.com/lihaoyi/Ammonite/issues/515

This is causing problems with my own use case of Ammonite (I use Pegdown...) and so I'd like to delay a stable release of Ammonite until I (or someone else) manages to sort that out. It's a bit unfortunate that this is blocked on a release of ammonite-ops when the bug is in ammonite-repl; maybe at some point we can break it off and have ammonite-ops be it's own repo and release cycle

**Comment by lihaoyi** [comment]
Since this is just using -ops and the bug is in -repl, and the code should be binary compatible anyway, we should probably just use the unstable version of Ammonite (e.g. `COMMIT-4032eee`) that is published for 2.12.1. It wouldn't hurt, and should be binary compatible with the current stable version, and when lihaoyi/Ammonite#515 is fixed it should be binary compatible with whatever comes after, so there would be no harm to do so.

Currently, Scalatex does not pass tests either on my own laptop or in CI, but if someone makes the tests pass, bumps Ammonite-Ops to an unstable version, and makes it work on 2.12.1, I'll happily kick off a release

**Comment by lihaoyi** [comment]
FWIW I created a Gitter chat room https://gitter.im/lihaoyi/Scalatex if anyone wants to talk about this

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/Ammonite/pull/525 should fix the problem with Ammonite; what remains is for someone to fix the Scalatex build and get it green for 2.12.x, and then I'll kick off a release

**Comment by lihaoyi** [comment]
Looks like this has happened
